_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: daf8d64e-c5c3-4b4f-aa25-d894c3a54862
name: 'Knitting Pattern Editor'
mail: margy@gurus.org
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
